# Generated by Django 3.1.12 on 2025-08-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorafi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='nodo',
            name='longitud',
        ),
    ]
