# Generated by Django 3.1.12 on 2025-08-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorafi', '0003_auto_20250825_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
