# Generated by Django 3.1.12 on 2025-08-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorafi', '0004_auto_20250825_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nodo',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
