# Generated by Django 3.1.12 on 2025-08-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorafi', '0005_auto_20250826_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
    ]
