# Generated by Django 3.1.12 on 2025-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorafi', '0006_nodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='dispositivos_img/'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='imei',
            field=models.CharField(default='IM-0', max_length=15),
        ),
    ]
