# Generated by Django 3.1.12 on 2025-09-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorafi', '0007_auto_20250904_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodo',
            name='ultima_vez_visto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
