name: loravil
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sidebarx: ^0.17.2
  animate_do: ^4.2.0
  loading_animation_widget: ^1.3.0
  animated_text_kit: ^4.2.3
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.10.0
  geolocator: 14.0.0
  custom_info_window: ^1.0.1
  #para OpenStreetMap
  latlong2: ^0.9.1
  flutter_map: ^8.1.1 
  flutter_map_location_marker: ^10.1.0
  location: ^8.0.0 
  http: ^1.4.0
  flutter_polyline_points: ^2.1.0
  babylonjs_viewer: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

